### ISSUE TITLE
Project should have a package.json

### ISSUE THREAD

**Issue by kieraneglin** [benjvmin/TinyPubSub#1]
A [package.json](https://docs.npmjs.com/files/package.json) will allow for publishing on the NPM registry, proper versioning, proper licensing, and let other's reference it from within their projects more easily.

I don't recommend receiving a pull request for this one.  It's very simple to do:

1. Install a Node package manager, such as Yarn or NPM (I prefer [Yarn](https://yarnpkg.com/en/))
2. Run its `init` function (`npm init` or `yarn init`)
3. Answer its questions

**Comment by benjvmin** [comment]
Hey kieraneglin, thanks for the issue! I actually did have a package.json, but I temporarily removed it as it had a list of dev dependencies from an older project that this was born out of. I'll add it again tomorrow! Thanks!
