### ISSUE TITLE
Project should have a proper license

### ISSUE THREAD

**Issue by kieraneglin** [benjvmin/TinyPubSub#2]
If anyone wants to use this in a non-personal project, they'd probably pass on it since the disclaimer in the code isn't "good enough" (legally speaking).

Judging by the disclaimer in the code, you probably want an MIT license.  Just create a file called `LICENSE` (no extension) and fill it in with the blurb found [here](https://opensource.org/licenses/MIT).

**Comment by benjvmin** [comment]
Perfect, thank you!
